### ISSUE TITLE
Некорректная цена YNDX

### ISSUE THREAD

**Issue by d0xin** [WLM1ke/poptimizer#1]
За 25.11 в программе:
YNDX    635.6000

Факт за 25.11: 
YNDX    2629

**Comment by d0xin** [comment]
Прошу прощения. Ошибка по всей видимости в другой библиотеке - aiomoex.

**Comment by d0xin** [comment]
REGNUMBER  LOTSIZE   SHORTNAME
SECID
ABRD   1-02-12500-A       10  АбрауДюрсо
AFKS   1-05-01669-A      100  Система ао
AFLT   1-01-00010-A       10    Аэрофлот
AGRO           None        1    AGRO-гдр
AKRN   1-03-00207-A        1       Акрон

          REGNUMBER  LOTSIZE   SHORTNAME
SECID
YNDX           None        1  Yandex clA
YRSB   1-01-50099-A       10     ТНСэнЯр
YRSBP  2-01-50099-A       10   ТНСэнЯр-п
ZILL   1-02-00036-A        1      ЗИЛ ао
ZVEZ   1-01-00169-D     1000   ЗВЕЗДА ао


Видимо из-за "None" и берется цена AGRO

**Comment by d0xin** [comment]
Переоткрою))) Похоже, что это всё таки поиск алиасов по регнамберу виновен.

**Comment by WLM1ke** [comment]
Формально переписать поиск алиасов не сложно, но есть следующая более крупная проблема. Бумаги без регистрационного номера - это депозитарные расписки на иностранные бумаги, которые платят дивиденды в иностранной валюте. Я, во-первых, по таким бумагам не вбивал информацию о дивидендах, а, во-вторых, надо очень много блоков перелопачивать для того, чтобы реализовать поддержку дивидендов в разных валютах. 

Для себя я решил, что на данном этапе не стоит с этим заморачиваться, и в своем портфеле не держу такие бумаги. 

По этому ишью вижу 3 возможных решения:
1. В поиске алиасов падать по исключению с сообщением об отсутствии поддержки таких бумаг.
2. В поиске алиасов выдавать ворнинг с сообщением об отсутствии полной поддержки таких бумаг - данные по дивидендам не ведутся.
3. Реализовать поддержку иностранных бумаг в полной мере. Но думаю до этого у меня руки дойдут очень не скоро.
