### ISSUE TITLE
Ошибка, предположительно, после удаления таблицы data.misc.trading_dates 

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#103]
Доброго времени суток!
Столкнулся с ошибкой при запуске evolve()
Начинается "Загрузка данных по торговым дням" , затем сохранение и ошибка (в приложенном txt файле)

Прочитал в одном из Issue, что данную таблицу можно удалять, насколько раз её удаление не мешало нормальному запуску программы.

Запуская повторно Evolve() запускается и обучает модели, но optimize() валится с ошибкой

**Comment by WLM1ke** [comment]
Не вижу файла

**Comment by vSINKS** [comment]
[issue.txt](https://github.com/WLM1ke/poptimizer/files/8017903/issue.txt)

**Comment by WLM1ke** [comment]
Произошло дробление нескольких [фондов](https://www.moex.com/n40216).

Нужно удалить в коллекции quotes данные по ним.

**Comment by vSINKS** [comment]
Принято, сейчас сделаю. По результатам отпишусь.

**Comment by vSINKS** [comment]
Получилось! 
Удалил из коллекции quotes 3 фонда: FXGD, FXTB, FXRU и коллекцию data.misc.trading_dates
Запустил - работает.
Большое спасибо за оперативный ответ!
