### ISSUE TITLE
ORUP переведен в категорию бумаг повышенного риска

### ISSUE THREAD

**Issue by chinser** [WLM1ke/poptimizer#104]
ORUP переведен в категорию бумаг повышенного риска c 11.02.2022 (https://www.moex.com/n40783?utm_source=www.moex.com&utm_term=orup), выдаёт KeyError "['ORUP']" not in index

**Comment by WLM1ke** [comment]
Знаю. Нужно удалить его из https://github.com/WLM1ke/poptimizer/blob/master/portfolio/base.yaml и переобучить модели.
