### ISSUE TITLE
Ошибка при смене тикеров фондов

### ISSUE THREAD

**Issue by gitRussel** [WLM1ke/poptimizer#110]
С недавнего времени начала вылазить ошибка, при запуске эволюции с новыми ВТБ (ВИМ) тикерами. При этом уже пробовал менять портфель на старые тикеры, вызывать метод add_tickers, но там новые предложены не были.

![image](https://user-images.githubusercontent.com/28735314/180943690-d0dba10f-7506-43a0-85af-4114715c2fd9.png)

**Comment by WLM1ke** [comment]
Если запускали на новой машине, то видимо проблема в том, что биржа обрезала старую историю по этой бумаге и теперь выдает ее со дня перехода на новый тикер. Могу сбросить документ с полной историей из моей базы

[eqmx.json.zip](https://github.com/WLM1ke/poptimizer/files/9187613/eqmx.json.zip)

**Comment by gitRussel** [comment]
Мне необходимо записать историю в базу? В какой таблице хранится история котировок?

**Comment by gitRussel** [comment]
Возможно я могу сменить тикеры в базе?

**Comment by WLM1ke** [comment]
Если у вас в базе есть котировки для старых тикеров, то конечно легче их просто переименовать на новые. Котировки хранятся в базе data в коллекции quotes

**Comment by gitRussel** [comment]
Перенёс историю в коллекциях quotes и dividends - помогло
