### ISSUE TITLE
Неверный заголовок: ('ивиденд,руб',) не входит в ['Дивиденд, руб']

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#111]
Добрый день!
Запулил себе сегодняшние исправления, для верности удалил из БД misc.trading_dates. При запуске evolve получаю ошибку 
poptimizer.data.adapters.html.description.ParserError: Неверный заголовок: ('ивиденд,руб',) не входит в ['Дивиденд, руб'] 
Попробовал внести исправления в файл smart_lab.py
https://github.com/WLM1ke/poptimizer/blob/4d8f29c61ba1c8f69848e8fa63636fc7868d78ca/poptimizer/data/adapters/gateways/smart_lab.py#L30

Ошибка ушла, но свалился уже на
File "/home/poptimizer/poptimizer/data/adapters/html/parser.py", line 68, in _validate_header
    raise description.ParserError(f"Неверный заголовок: {desc.raw_name} не входит в {header}")
poptimizer.data.adapters.html.description.ParserError: Неверный заголовок: ('Эмитент',) не входит в ['Скачать данные в формате:']
make: *** [makefile:37: run_evolve] Ошибка 1

**Comment by vSINKS** [comment]
Исправление заключалось в добавлении пробела. В теории, можно победить эту ошибку если в сравнении удалять все пробелы из сравниваемого значения. Тогда не понадобится добавлять пробел.

**Comment by WLM1ke** [comment]
Погляжу. По опыту SmartLab редко меняется, поэтому легче пробел убрать

**Comment by vSINKS** [comment]
TABLE_INDEX, вроде как, снова на 3 поменялся, я изменил на 3  - ушли ошибки "Неверный заголовок: ('Эмитент',) не входит в ['Скачать данные в формате:']" и данные успешно скачались.

**Comment by WLM1ke** [comment]
Да, фигово, когда дизайн меняют:)

**Comment by vSINKS** [comment]
Есть предложение по доработке, индекс задавать значением по умолчанию, плюс разработать функцию, которая будет перебирать все таблицы на странице и отбирать индекс той, в которой имеются необходимые поля "эмитент" и пр. Если индекс переменной не совпадает с найденным - переопределять на новое значение.

**Comment by WLM1ke** [comment]
Я тут пишу новую версию. Если честно нет желание в текущей чего-то существенное менять - скорее поддерживать мелкими правками

**Comment by vSINKS** [comment]
Ок, к версии на python вопросов нет. Возможно предложенное исправление потребуется в "новой" версии.

**Comment by WLM1ke** [comment]
Там в основном из json забираются данные, а не прямо HTML страничек
