### ISSUE TITLE
Ошибка после: более жесткий отбор при превышении популяцией 100

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#113]
Добрый день!
Обновил приложение до последней версии version_2, при запуске эволюции получил ошибку (во вложении).
[ErrLog.txt](https://github.com/WLM1ke/poptimizer/files/9844114/ErrLog.txt)

**Comment by WLM1ke** [comment]
Поправил - думаю должно помочь

**Comment by vSINKS** [comment]
Исправление помогло. Спасибо за оперативное решение!
