### ISSUE TITLE
RET —  0.0000:  0.0000,  0.0000,  0.0000, -0.0000, 

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#114]
Добрый день!
Это нормально, что при эволюции все значения RET -  нулевые? 

ime.datetime(2022, 10, 23, 11, 1, 11, 994047))
***2022-10-21: Шаг эволюции — 2***
LLH - (1.9550, 2.2375, 2.3479)
RET - (-0.1266, 0.0000, 0.1098)
Организмов - 90 / Максимум оценок - 328
Тестов - 266

Родитель:
LLH —  1.9550:  2.2664,  2.0500,  1.8197,  1.7906,  1.5992,  1.6143,  1.4972,  0.8572,  1.4274,  1.5102,  1.1641,  1.2892,  1.4103,  1.0739,  1.3880,  1.5615,  1.5019,  1.4010,  1.3958,  1.6443,  1.5014,  1.5594,  0.4626,  0.5274, -0.1652,  0.0729, -0.1365,  0.3300, -1.7423,  2.1759,  1.9874,  2.3726,  2.3955,  2.2833,  2.0314,  2.1031,  2.1662,  2.4230,  2.2036,  2.1555,  2.0065,  2.0213,  2.0810,  2.2036,  2.2751,  2.0654,  1.9648,  1.8718,  2.2201,  1.9964,  2.1578,  2.0086,  2.0708,  1.9315,  2.1669,  2.3177,  1.9323,  2.2201,  1.8904,  1.9068,  2.2320,  1.7803,  1.7595,  1.9206,  1.8608,  2.0948,  2.1588,  1.8363,  2.1304,  1.9877,  2.0626,  2.1660,  2.0954,  1.9913,  2.0891,  1.8855,  2.1079,  1.7841,  2.0517,  1.8163,  2.0484,  2.2428,  1.9708,  1.8777,  1.9360,  1.9255,  2.0897,  1.7841,  2.2473,  2.0001,  2.2615,  2.2616,  1.9614,  2.0257,  1.9650,  2.0426,  2.0102,  2.0713,  1.8782,  2.0432,  1.9515,  1.8857,  1.8958,  1.7736,  1.9489,  2.0472,  2.1977,  2.2149,  1.7602,  2.1065,  1.7516,  1.6702,  1.9490,  1.8310,  2.1340,  1.6707,  1.8081,  1.9585,  2.0090,  1.9847,  2.2369,  2.1910,  1.8455,  2.1971,  1.9148,  1.8783,  2.0561,  1.9378,  1.9189,  2.0227,  2.3463,  2.1910,  2.2029,  1.8960,  1.8730,  1.7661,  1.6932,  1.9854,  1.7537,  1.7631,  1.8773,  1.7120,  1.8828,  1.8177,  1.9602,  1.7956
RET —  0.0000:  0.0000,  0.0000,  0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000,  0.0000, -0.0000, -0.0000,  0.0000, -0.0000,  0.0000,  0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,  0.0000,  0.0000, -0.0000, -0.0000,  0.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.0000, -0.0000, -0.0000,  0.0000,  0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.0000, -0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.0000, -0.0000, -0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000,  0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000
Timer — 0:00:29 / Scores - 146
Data: {'batch_size': 5143.928256972255, 'history_days': 146.46386740909378, 'ticker_on': -51604423.12967946, 'day_of_year_on': 1150.4434190187294, 'day_of_period_on': -88753977560.59207, 'prices_on': -71269365.68904419, 'dividends_on': -10673813.469987487, 'turnover_on': -3343897.4782280354, 'average_turnover_on': -23609482.36791987, 'rvi_on': -1871623727.1106746, 'mcftrr_on': -4707151679.90672, 'imoex_on': -49460735.62711218, 'ticker_type_on': -8430956.61195691, 'usd_on': -970628209.3099196, 'open_on': -7652411.884616042, 'high_on': -9573744.544960594, 'low_on': -1155023.8337775373, 'meogtrr_on': 352635.8934807548}
Model: {'start_bn': 485164.9363186527, 'kernels': 11.14078683933462, 'sub_blocks': 1.6080628388586975, 'gate_channels': 9.110646611032175, 'residual_channels': 3.4621416629947825, 'skip_channels': 11.347704878580332, 'end_channels': 81.37909162677143, 'mixture_size': 375.057191626477}
Optimizer: {'betas': 0.9998752404087369, 'eps': 0.0005234983244353638, 'weight_decay': 3.663048488551032}
Scheduler: {'max_lr': 0.002654456820168195, 'epochs': 0.9906896868314652, 'pct_start': 0.2430249828940383, 'anneal_strategy': -58763860383.05569, 'base_momentum': 0.8314377732920282,

**Comment by WLM1ke** [comment]
Такое бывает.

**Comment by vSINKS** [comment]
Спасибо!
