### ISSUE TITLE
version_2. Ошибка при загрузке trading_dates

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#115]
Доброго времени суток!
На прошлой неделе в ветке version_2 сломалась загрузка trading_dates.
Самому поправить не удалось :(
Во вложении файл с текстом ошибки.
[err.txt](https://github.com/WLM1ke/poptimizer/files/10157594/err.txt)

**Comment by WLM1ke** [comment]
У вас последняя версия?

**Comment by vSINKS** [comment]
Перепроверил, оказалось что не последняя (ошибочно решил, что крайние исправления были только для ветки master и обошли стороной version_2. После git pull данные успешно загрузились, но образовалась другая ошибка, файлы во вложении.
Несмотря на ошибку, эволюция со второго раза запустилась.

[err20221206_2.txt](https://github.com/WLM1ke/poptimizer/files/10169175/err20221206_2.txt)
[err20221206.txt](https://github.com/WLM1ke/poptimizer/files/10169176/err20221206.txt)

**Comment by WLM1ke** [comment]
Напишите, если снова упадет - может это какие-то глюки после предыдущего падения.

**Comment by WLM1ke** [comment]
Воспроизвел у себя ошибку - надо зайти в базу в коллекцию quotes и удалить документ с id AKQU

**Comment by vSINKS** [comment]
Выполнил следующий кейс:
- остановил эволюцию
- удалил trading_dates
- запустил эволюцию, началась загрузка данных и упала с ошибкой
- удалил, по рекомендации выше, AKQU из коллекции quotes
- удалил trading_dates
- запустил эволюцию, началась загрузка данных и упала с ошибкой уже на TSPV
- удалил, TSPV из коллекции quotes
- удалил trading_dates
- запустил эволюцию, началась загрузка данных, и запустилась эволюция в штатном режиме. 

Спасибо!

**Comment by WLM1ke** [comment]
Альфовский фонд несколько дней назад отвалился
