### ISSUE TITLE
Нет пакетов для  Nvidia Cuda

### ISSUE THREAD

**Issue by michael-xiii** [WLM1ke/poptimizer#116]
Macbook Pro 2019, Intel UHD Graphics 630 1536 MB, Ventura

Poetry не может найти пакеты для nvidia (что выглядит логично)

Unable to find installation candidates for nvidia-cublas-cu11 (11.10.3.66)

  at /usr/local/Cellar/poetry/1.2.2_1/libexec/lib/python3.11/site-packages/poetry/installation/chooser.py:103 in choose_for
       99│
      100│             links.append(link)
      101│
      102│         if not links:
    → 103│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      104│
      105│         # Get the best link
      106│         chosen = max(links, key=lambda link: self._sort_key(package, link))
      107│

  • Installing nvidia-cuda-nvrtc-cu11 (11.7.99): Failed

  RuntimeError

  Unable to find installation candidates for nvidia-cuda-nvrtc-cu11 (11.7.99)

  at /usr/local/Cellar/poetry/1.2.2_1/libexec/lib/python3.11/site-packages/poetry/installation/chooser.py:103 in choose_for
       99│
      100│             links.append(link)
      101│
      102│         if not links:
    → 103│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      104│
      105│         # Get the best link
      106│         chosen = max(links, key=lambda link: self._sort_key(package, link))
      107│

  • Installing nvidia-cuda-runtime-cu11 (11.7.99): Failed

  RuntimeError

  Unable to find installation candidates for nvidia-cuda-runtime-cu11 (11.7.99)

  at /usr/local/Cellar/poetry/1.2.2_1/libexec/lib/python3.11/site-packages/poetry/installation/chooser.py:103 in choose_for
       99│
      100│             links.append(link)
      101│
      102│         if not links:
    → 103│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      104│
      105│         # Get the best link
      106│         chosen = max(links, key=lambda link: self._sort_key(package, link))
      107│

  • Installing nvidia-cudnn-cu11 (8.5.0.96): Failed

  RuntimeError

  Unable to find installation candidates for nvidia-cudnn-cu11 (8.5.0.96)

  at /usr/local/Cellar/poetry/1.2.2_1/libexec/lib/python3.11/site-packages/poetry/installation/chooser.py:103 in choose_for
       99│
      100│             links.append(link)
      101│
      102│         if not links:
    → 103│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      104│
      105│         # Get the best link
      106│         chosen = max(links, key=lambda link: self._sort_key(package, link))
      107│

make: *** [update] Error 1

**Comment by WLM1ke** [comment]
Знаю о такой проблеме - poetry не умеет ставить torch 1.13 на мак.
Автор poetry пишет, что на его стороне все нормально - он строго соблюдает стандарты и ничего не собирается менять, а проблема на стороне кривого инсталлятора torch, при это pull request не принимают.

В общем понизил версию torch до 1.12 - должна ставиться.
