### ISSUE TITLE
Ошибка при загрузке. 

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#119]
Доброго времени суток!
Заметил, что эволюция перестала работать, видимо, сломалась при загрузке. При перезапуске получаю ошибку.
Лог ошибки во вложении.
[make_run_evolve.txt](https://github.com/WLM1ke/poptimizer/files/10450794/make_run_evolve.txt)

**Comment by vSINKS** [comment]
Спасибо!
Помогло удаление data.indexes.MCFTRR и data.indexes. MEOGTRR
Затем удалил data.misc.trading_dates и перезапустил эволюцию.

**Comment by WLM1ke** [comment]
Еще надо ROLO грохнуть - произошло дробление.

**Comment by vSINKS** [comment]
> Еще надо ROLO грохнуть - произошло дробление. 

Удалил вчера, спасибо!
