### ISSUE TITLE
KeyError: 'timer'. Ошибка при запуске эволюции. ver 2

### ISSUE THREAD

**Issue by gitRussel** [WLM1ke/poptimizer#120]
![image](https://user-images.githubusercontent.com/28735314/213858221-ba0f3b9e-6dc4-4609-9d08-dd16b51cf3b1.png)

Ошибка при каждом запуске эволюции, не понимаю как её решить

**Comment by WLM1ke** [comment]
Можно найти документ c моделью без поля timer и удалить его.

Так же запушил версию, где эта ситуация вроде должно обрабатываться корректно.

**Comment by gitRussel** [comment]
Да, всё хорошо, спасибо
