### ISSUE TITLE
Как восстановить данные?

### ISSUE THREAD

**Issue by gitRussel** [WLM1ke/poptimizer#122]
Добрый день, случайно удалил данные в data.dividends как я могу их восстановить?
Постоянно ловлю ошибку при запуске эволюции 

> poptimizer.data.app.viewers.NoDFError: ('dividends', 'AFKS')

**Comment by WLM1ke** [comment]
Попробуйте в коллекции misc удалить документ trading_dates. Данные по идее перенальются

**Comment by gitRussel** [comment]
Вроде восстановилось, но пришлось исключать ENRU из перечня бумаг из-за ошибки

> poptimizer.data.app.viewers.NoDFError: ('dividends', 'ENRU')

**Comment by WLM1ke** [comment]
Похоже его переименовали в ELFV, но это так просто не исправить - проще исключить
