### ISSUE TITLE
Неверные значение price

### ISSUE THREAD

**Issue by gitRussel** [WLM1ke/poptimizer#123]
Доброго времени суток, пользуюсь второй версией poptimizer'а недавно заметил, что данные по ценам неверные. Как обновить?
![image](https://github.com/WLM1ke/poptimizer/assets/28735314/5e21c9b9-3d16-4334-9ead-32549f001ea7)

**Comment by WLM1ke** [comment]
Честно говоря, какая-то странная ситуация. У вас в базе какие значения за последнии несколько дней по LKOH и за какие дни данные, например?

**Comment by gitRussel** [comment]
> Честно говоря, какая-то странная ситуация. У вас в базе какие значения за последнии несколько дней по LKOH и за какие дни данные, например?

В какой бд и коллекции посмотреть данные?

**Comment by WLM1ke** [comment]
data.quotes

**Comment by gitRussel** [comment]
По LKOH
![image](https://github.com/WLM1ke/poptimizer/assets/28735314/27678f45-866e-4205-bb35-6cf113543e2a)

**Comment by WLM1ke** [comment]
И ще вопросик - можете сказать, что у вас в data.misc.trading_dates?

**Comment by WLM1ke** [comment]
Там документ небольшой - раскройте все поля

**Comment by gitRussel** [comment]
> И ще вопросик - можете сказать, что у вас в data.misc.trading_dates?

![image](https://github.com/WLM1ke/poptimizer/assets/28735314/d84d81f6-b19f-4d9d-b129-8c7ddcd04cad)

**Comment by WLM1ke** [comment]
А у вас точно моя версия стоит - потому что, у меня этот документ несколько иную структуру имеет? 
Может это какой-то форк переделанный?
Как давно пользуетесь?

Учитывая, что по косвенным признакам это не моя версия, и само поведение крайне странное, тут сложно чего-то рекомендовать, но в моем версии, если этот документ дрогнуть, то данные должны докалиться до актуальных.

**Comment by gitRussel** [comment]
Да, уже давно пользуюсь, какую коллекцию удалить и какой командой?

**Comment by WLM1ke** [comment]
Вот этот документ удалите, который вы последним показывали - data.misc.trading_dates. Просто у вас явно версия отличается от моей, и если вы пользуетесь давно, то данные у вас полгода не обновляются судя по LKOH. Поэтому тут скорее надо разбираться, где и как у вас версия поломана

**Comment by gitRussel** [comment]
Удалил, прошла загрузка данных, но в quotes остались данные за июль... Ветки с помощью git diff - ничего криминального не нашёл, только различие в конфигах и файлах poetry.lock

**Comment by WLM1ke** [comment]
Выглядит это все крайне странно. А у вас загрузка нормально прям до конца дошла?

**Comment by WLM1ke** [comment]
И как выглядит документ, который вы удаляли после обновления?

**Comment by gitRussel** [comment]
Теперь падает загрузка

![image](https://github.com/WLM1ke/poptimizer/assets/28735314/ffa7cd11-b879-4388-a5e1-dc45d4008521)

**Comment by gitRussel** [comment]
> И как выглядит документ, который вы удаляли после обновления?

![image](https://github.com/WLM1ke/poptimizer/assets/28735314/e1722be5-bc84-446a-a4d5-c240d4010737)

**Comment by WLM1ke** [comment]
А в предыдущие дни у вас не падало при обновление - у меня только одно рациональное объяснение, что падает у вас где-то с июля при обновлении?

**Comment by gitRussel** [comment]
Я в июле запускал - всё ок было, и тогда я вроде что-то делал с базой. И сейчас заново хотел запустить эволюцию, обновил ветку и вот столкнулся с ошибками.

**Comment by WLM1ke** [comment]
То есть вы где-то полгода не пользовались, а сейчас запустили. Тогда понятно как это полечить. Некоторые бумаги иногда дробятся, в результате при заливке новых данных котировки не стыкуются. Нужно удалить данные по таким бумагам - лежат они в data.quotes. Название бумаги в сообщении об ошибке видно. Но думаю за пол года там несколько таких есть, так что прийдется несколько раз попробовать и подчистить все по очереди

**Comment by gitRussel** [comment]
А, хорошо, обновлю, может можно будет такую операцию сделать в автоматическом режиме, если в исключении есть имя бумаги и имя коллекции?

**Comment by WLM1ke** [comment]
Не очень понял, что вы хотели сказать

**Comment by gitRussel** [comment]
При запуске падает исключение, вместо исключение можно было бы написать функцию, которая вычищает данные из БД по этой бумаге.

**Comment by WLM1ke** [comment]
Нет, такая задумка была, чтобы в случае каких-то непоняток падало, чтобы данные не закораптились. А уж потом ручками идешь смотреть и если, расхождению есть понятное объяснение, то удаляешь старые данные

**Comment by gitRussel** [comment]
Понял, хорошо, спасибо
