### ISSUE TITLE
Ошибка после ночной загрузки данных "cannot schedule new futures after shutdown".

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#126]
Добрый день!
Недавано подпулился из репозтория, 2 ночи подряд получаю  ошибку:
"cannot schedule new futures after shutdown".
Возможно связано  с тем, что давно не обновлял пакеты через  Poetry
Ошибка во вложении.
[error_20240221.txt](https://github.com/WLM1ke/poptimizer/files/14355007/error_20240221.txt)

Процесс крутится на Ubuntu 20.04 (работает там давно и без нареканий).

**Comment by WLM1ke** [comment]
А это весь стектрейс ошибки? Есть подозрение, что только часть, и это только последствие основной ошибки, которая где-то в самом начале

**Comment by vSINKS** [comment]
Удалил  trading dates  для повторения ошибки. Полный  файл во  вложении.
[error_20240221_2.txt](https://github.com/WLM1ke/poptimizer/files/14356162/error_20240221_2.txt)

**Comment by WLM1ke** [comment]
По GEMA данные не стыкуются из-за сплита - удалите ее котировки

**Comment by vSINKS** [comment]
Благодарю,  помогло  удаление из quotes  бумаг GEMA и  TRNFP.
