### ISSUE TITLE
version_2. "AttributeError: 'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#129]
Добрый вечер!
По моим наблюдениям, с прошлой недели стала появляться ошибка "AttributeError: 'NoneType' object has no attribute 'group'" при запуске "make run_evolve".
Лог с ошибкой прикладываю. Срочности никакой нет, просьба посмотреть, по возможности.
Спасибо!
[20240325.log.txt](https://github.com/WLM1ke/poptimizer/files/14747949/20240325.log.txt)

**Comment by WLM1ke** [comment]
А какая у вас версия? Конкретно, что содержится в 18 строке /home/User/poptimizer_v2/poptimizer/data/adapters/gateways/cpi.py?

**Comment by vSINKS** [comment]
Ветка репозитория version_2:

"""Загрузка данных по потребительской инфляции."""
import re
import types

import aiohttp
import pandas as pd

from poptimizer import config
from poptimizer.data.adapters.gateways import gateways
from poptimizer.shared import adapters, col

# Параметры загрузки валидации данных
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15",
}
_PRICES_PAGE = "https://rosstat.gov.ru/statistics/price"
_RE_FILE = re.compile(r"/[iI]pc[\-_]mes[\-_][0-9]{1,2}.xlsx")
_URL = "https://rosstat.gov.ru/storage/mediabank/{}"
END_OF_JAN = 31
PARSING_PARAMETERS = types.MappingProxyType(
    {
        "sheet_name": "01",
        "header": 3,
        "skiprows": [4],
        "skipfooter": 5,
        "index_col": 0,
        "engine": "openpyxl",
    },
)
NUM_OF_MONTH = 12
FIRST_YEAR = 1991
FIRST_MONTH = "январь"

**Comment by WLM1ke** [comment]
У вас не последняя версия - произошли изменения на сайте, где публикуется CPI. Я пару недель назад фикс выпустил под это изменение - обновите версию

https://github.com/WLM1ke/poptimizer/blob/version_2/poptimizer/data/adapters/gateways/cpi.py#L18

**Comment by vSINKS** [comment]
Делал merge в локальную ветку из version_2, видимо что-то пошло не так. С актуальной версией работает без ошибок, благодарю!
