### ISSUE TITLE
ValueError: Length mismatch: Expected axis has 0 elements, new values have 4 elements

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#130]
Добрый день!
Обнаружил сегодня ошибку в логах, при перезапуске получаю ошибки (приложен лог
[20240402.log.txt](https://github.com/WLM1ke/poptimizer/files/14834342/20240402.log.txt)
)

**Comment by WLM1ke** [comment]
Я утром новую версию залил, для фикса этой проблемы - у вас она или более старая?
