### ISSUE TITLE
Стирается вся популяция. Version_2

### ISSUE THREAD

**Issue by gitRussel** [WLM1ke/poptimizer#133]
Последние два дня не могу запустить эволюцию, при запуске удаляется вся популяция с такими сообщениями:
![image](https://github.com/user-attachments/assets/86479892-acbd-466f-9782-d59c2ae4fef0)

Удаляется последний организм, программа завершает работу с таким сообщением:
![image](https://github.com/user-attachments/assets/31895629-85c4-47b8-bf64-d703a7270123)

**Comment by WLM1ke** [comment]
Подозреваю, у вас свой набор бумаг и в нем какая-то с короткой историей - например новый Яндекс

**Comment by gitRussel** [comment]
Есть скрипт к mongoDB, чтобы найти список бумаг, с короткой историей? 
Или может, где-то в ошибке писать, что на конкретной бумаге происходит падение, при итерации?

**Comment by WLM1ke** [comment]
Если дернуть этот [метод](https://github.com/WLM1ke/poptimizer/blob/82bd870f8625d8a4d5f35c19dab60c4ee58961b2/poptimizer/portfolio/portfolio.py#L218), то он даст список бумаг на удаление из-за короткой истории или низкой ликвидности

**Comment by gitRussel** [comment]
Я не представляю, как дернуть метод

**Comment by gitRussel** [comment]
```
from poptimizer import portfolio
p = portfolio.load_from_yaml("2024-09-19")
print(p.remove_tickers())
```
Вот так получилось вывести список
