### ISSUE TITLE
Ошибка в тегах репозитория.

### ISSUE THREAD

**Issue by palsol** [WLM1ke/poptimizer#39]
Добрый день. У вас ошибка в теге репозитория (это ерунда конечно но все же).
deap-learning -> deep-learning

**Comment by ikonushok** [comment]
спасибо огромное! )) начинал совсем зеленым, учусь

> 24 авг. 2020 г., в 11:14, Pavel <notifications@github.com> написал(а):
> 
> deep-learning

**Comment by WLM1ke** [comment]
@palsol поправил
