### ISSUE TITLE
Сломается если в портфеле нет открытых позиций.

### ISSUE THREAD

**Issue by palsol** [WLM1ke/poptimizer#41]
Сломается если в портфеле нет открытых позиций.
https://github.com/WLM1ke/poptimizer/blob/853ad1c6be4a73530e01c650a4386254fccdd387/poptimizer/portfolio/portfolio.py#L69

**Comment by WLM1ke** [comment]
@palsol я в основном с полностью инвестированными портфелями имею дело, но на всякий случая поправил
