### ISSUE TITLE
Unreal LLH, which fails on eval, but always wins in evolve.

### ISSUE THREAD

**Issue by RomaKoks** [WLM1ke/poptimizer#42]
***2020-10-01: Шаг эпохи - 100/100***
LLH - (2.0130, 2.1284, 26548.4739)
Максимум побед - 30

Родитель:
Побед - 30
Data: {'batch_size': 127.45135180958202, 'history_days': 253.82088632293883, 'ticker_on': -2.127426227385521, 'day_of_year_on': -5.0167343543925575, 'day_of_period_on': 0.1399657547039146, 'prices_on': -1.7791840595416208, 'dividends_on': -2.5585755251108013, 'turnover_on': -3.2084742407103635, 'average_turnover_on': -0.22674459319728557}
Model: {'start_bn': -2.1176982922820216, 'kernels': 2.300783417110007, 'sub_blocks': 1.360626893510361, 'gate_channels': 2.460099421116139, 'residual_channels': 5.8362842700907, 'skip_channels': 5.782226700386957, 'end_channels': 2.127746428553457}
Optimizer: {'betas': 0.9991061935123207, 'eps': 1.009124393366369e-08, 'weight_decay': 0.010240856523939598, 'amsgrad': 3.3038695826083053}
Scheduler: {'max_lr': 0.010750924886635432, 'epochs': 1.004782005843315, 'pct_start': 0.3038539102518628, 'anneal_strategy': 0.47784917341259225, 'base_momentum': 0.8558587213774674, 'max_momentum': 0.9469542283955424, 'div_factor': 24.67513505453672, 'final_div_factor': 10421.271524928849}
**LLH: 26548.4739**
Timer: 45

Потомок:
Побед - 0
Data: {'batch_size': 127.45135180958202, 'history_days': 280.89739122307157, 'ticker_on': -22.0823140380744, 'day_of_year_on': -0.4995328699316497, 'day_of_period_on': 6.173325860767405, 'prices_on': 2.73561726442144, 'dividends_on': -67.65783995739321, 'turnover_on': 34.62113859021244, 'average_turnover_on': 10.105738046802282}
Model: {'start_bn': 4.880492776786426, 'kernels': 2.003447537341679, 'sub_blocks': 1.0364606635047944, 'gate_channels': 2.460099421116139, 'residual_channels': 15.16052058481371, 'skip_channels': 4.301512677524137, 'end_channels': 9.311633520507543}
Optimizer: {'betas': 0.9982990880714625, 'eps': 1.0243818093682281e-08, 'weight_decay': 0.019987539992897638, 'amsgrad': 19.496689755005246}
Scheduler: {'max_lr': 0.0022085446585436604, 'epochs': 1.0244479512664655, 'pct_start': 0.3345462730031154, 'anneal_strategy': -1.3506650286263788, 'base_momentum': 0.8439443332526304, 'max_momentum': 0.9448479477272338, 'div_factor': 27.007370575496044, 'final_div_factor': 7894.043358954786}
Количество слоев - 102
Количество параметров - 10677
Epochs - 1.02
Train size - 128412
~~> Train: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1037/1037 [01:00<00:00, 17.00it/s, 1.50460]
Тестовых дней: 1
Тестовых примеров: 115
~~> Test: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 29.90it/s, 1.81867]
STD: 0.0348
LLH: 1.8187
Timer: 62

Более слабый и наиболее медленный - удаляю:
Побед - 1
Data: {'batch_size': 127.45135180958202, 'history_days': 280.89739122307157, 'ticker_on': -22.0823140380744, 'day_of_year_on': -0.4995328699316497, 'day_of_period_on': 6.173325860767405, 'prices_on': 2.73561726442144, 'dividends_on': -67.65783995739321, 'turnover_on': 34.62113859021244, 'average_turnover_on': 10.105738046802282}
Model: {'start_bn': 4.880492776786426, 'kernels': 2.003447537341679, 'sub_blocks': 1.0364606635047944, 'gate_channels': 2.460099421116139, 'residual_channels': 15.16052058481371, 'skip_channels': 4.301512677524137, 'end_channels': 9.311633520507543}
Optimizer: {'betas': 0.9982990880714625, 'eps': 1.0243818093682281e-08, 'weight_decay': 0.019987539992897638, 'amsgrad': 19.496689755005246}
Scheduler: {'max_lr': 0.0022085446585436604, 'epochs': 1.0244479512664655, 'pct_start': 0.3345462730031154, 'anneal_strategy': -1.3506650286263788, 'base_momentum': 0.8439443332526304, 'max_momentum': 0.9448479477272338, 'div_factor': 27.007370575496044, 'final_div_factor': 7894.043358954786}
LLH: 1.8187
Timer: 62

**Comment by RomaKoks** [comment]
Forecasts: 99it [01:19,  1.25it/s]
Length of passed values is 14605, index implies 115.

**Comment by WLM1ke** [comment]
Не очень понимаю, что у вас за версия - почему 115, а не 114. Не уверен, что удасться это починить. Легче грохнуть его в базе.

**Comment by RomaKoks** [comment]
115, возможно, потому что добавил другие тикеры? А как получился такой LLH?

**Comment by WLM1ke** [comment]
Честно сказать, у меня такого никогда не было. Есть подозрение, что в этом варианте мутации отключены все признаки (кроме одного) и там что-то нехорошее происходит с размерностью тензора из-за этого, поэтому llh неверно считается. 
Но на последней версии я такое не смог воспроизвести - у меня вполне адекватный llh получается. 

Мне кажется, его лучше в ручную грохнуть в MongoDB.

**Comment by RomaKoks** [comment]
А как его правильнее грохнуть? Просто удалить запись с моделью?

**Comment by RomaKoks** [comment]
У меня последняя версия это выдала.

**Comment by WLM1ke** [comment]
Я три раза на последней пытался и у меня все время что-то адекватное получалось. Да можно просто грохнуть запись с этой моделью. Программа при следующем запуске доведет количество моделей до 100.

**Comment by RomaKoks** [comment]
Получилось, спасибо!

**Comment by WLM1ke** [comment]
Я тут подумал, что может реально проблема с тикерами, которые вы добавили. Может котировки по ним какие-то битые, поэтому у меня не воспроизводится.

**Comment by RomaKoks** [comment]
я в base убрал: ENPG
добавил: BISVP, URKZ

**Comment by WLM1ke** [comment]
Вроде у них нет проблем с котировками, тогда не знаю:(

**Comment by RomaKoks** [comment]
может быть добавить костыль что если у модели не получилось сделать предикт - удалить её / заменить на другую / не использовать в текущем предикте?

**Comment by WLM1ke** [comment]
На сам деле, там стоит нечто похожее на определенные понятные ошибки - если не удается сделать придикт модель убивается.
https://github.com/WLM1ke/poptimizer/blob/ea9026c168968377ad35bf0571eccc503b6f8a5f/poptimizer/evolve/population.py#L126
Но по хорошему такое стоит ставить на понятные ситуации, а не на все. Если это разово возникло, то наверное не стоит с этой ошибкой возиться, а если ее появится, надо понять в чем причина, а потом причина.

**Comment by RomaKoks** [comment]
судя по всему - она вылетала строчкой ранее из-за несоответствия размерностей. Вопрос не по теме: я правильно понял, что дивиденды автоматически только сравниваются, а добавлять их нужно вручную? Если да, то как их правильно добавить?

**Comment by WLM1ke** [comment]
Надежных источников по дивидендам нет - приходится вбивать руками, а имеющиеся источники использовать на всякий случай для визуального сравнения. 

В MongoDB есть база source, а в ней коллекция dividends - там думаю все понятно без пояснений. В ней хранятся дивиденды, которые реально используются для расчетов.

**Comment by RomaKoks** [comment]
спасибо!

**Comment by RomaKoks** [comment]
Еще один оффтоп: предложение добавить в config 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
и в обучении использовать его, чтобы разгрузить cpu слегка, если есть возможность.

**Comment by WLM1ke** [comment]
Я не очень в этом силен и ускорителя у меня нет, чтобы протестить, что работает.
Без проблем впишу, только подскажите куда или PR направьте.

**Comment by RomaKoks** [comment]
> Надежных источников по дивидендам нет
а были примеры, когда dohod говорил неправду? Предложение: принять какой-то источник как истинный, и, если на другом источнике обнаружены противоречивые данные, уведомить о необходимости ручной верификации.

**Comment by WLM1ke** [comment]
dohod очень плохой источник- там нет многих дивидендов. Начинаются с разных дат данные. СТранным образом исчезают старые данные, а потом могут появиться. 

А в чем проблема с текущим подходом - я стараюсь регулярно вбивать новые? Покрытие по всем бумагам, которые указаны в файле портфеля. Если нужно добавить пару бумаг, то мне не сложно их внести и потом отслеживать.

**Comment by WLM1ke** [comment]
Эта функция автоматически запускается каждый раз при запуске. Если нет базы "source", то заливается наиболее актуальные данные

https://github.com/WLM1ke/poptimizer/blob/e5d0f2c28de25568e4515b63aaad4aa337e2e522/poptimizer/store/mongo.py#L60

**Comment by RomaKoks** [comment]
> Начинаются с разных дат данные

Если я правильно понял, модели получают на вход данные, обрезанные по времени (например, 250 торговых дней, обычно меньше) при этом если в списке тикеров существует Тикер, по которому нет данных на столько дней, то вся модель бракуется с TooLongHistoryError. Из этого делаю вывод, что данные по дивидендам более чем 2х летней давности никак не учитываются - это так?

**Comment by WLM1ke** [comment]
Нет это не так (или не совсем так) - данные обрезаны с начала 2015 года, когда торги по всем бумагам перешли в режим T+2. 
В сеть естественно подаются котировки за фиксированное число дней. Соответсвенно если бумага торгуется с 2015г будет подано много обучающих примеров по 250 (условно) дней каждый. 
Если по какая-то бумага торгуется относительно не давно и нельзя создать хотя бы один обучающий пример нужной длинны, то модель будет забракована, так как она ничего не сможет "выучить" для данной бумаги.

**Comment by RomaKoks** [comment]
А что в конечном счете пытаются предсказать модели? 
Я так понял, что параметры нормального распределения (m, s), но не понял распределение чего, как формируется target (Label)?

**Comment by RomaKoks** [comment]
https://bcs-express.ru/dividednyj-kalendar?year=2020 - что можете сказать по поводу этого источника дивидендов?

**Comment by WLM1ke** [comment]
target - доходность в следующие несколько дней.

Про этот источник ничего не могу сказать - не удобно, что нельзя посмотреть дивиденды по конкретной бумаге в историческом разрезе

**Comment by RomaKoks** [comment]
> нельзя посмотреть дивиденды по конкретной бумаге в историческом разрезе

они есть в коде страницы
![изображение](https://user-images.githubusercontent.com/8873242/95477454-07c21580-0991-11eb-8e49-b01e2f4c1cb7.png)

**Comment by WLM1ke** [comment]
Тогда надо проанализировать насколько там данные хорошие и полные. Нужен парсер данных, потом сравнить против текущих данных.

**Comment by RomaKoks** [comment]
ок, тогда я займусь парсингом

**Comment by WLM1ke** [comment]
Отлично.

**Comment by RomaKoks** [comment]
снова появился такой (примерно 2 дня непрерывного обучения):

***2020-10-09: Шаг эпохи - 100/100***
LLH - (1.9071, 1.9781, 23731.1071)
Максимум побед - 59

Родитель:
Побед - 16
Data: {'batch_size': 127.84522669010887, 'history_days': 256.54051635570454, 'ticker_on': -1.180884759987296, 'day_of_year_on': 0.6975643160785157, 'day_of_period_on': -5.759247962367275, 'prices_on': -2.337287969756517, 'dividends_on': -0.2846551984082666, 'turnover_on': -9.175464379611629, 'average_turnover_on': -3.899272554765735}
Model: {'start_bn': -0.5858115877491379, 'kernels': 2.812774639440735, 'sub_blocks': 1.2711504198826422, 'gate_channels': 8.426068831454481, 'residual_channels': 6.41275501389536, 'skip_channels': 6.430199423705021, 'end_channels': 1.7815749392638613}
Optimizer: {'betas': 0.9989755762733485, 'eps': 1.0163436860261087e-08, 'weight_decay': 0.009499259232411374, 'amsgrad': 5.184027403507773}
Scheduler: {'max_lr': 0.0036703808395230045, 'epochs': 0.9938216897066743, 'pct_start': 0.30882304233291424, 'anneal_strategy': 2.6056870614103578, 'base_momentum': 0.847926507191098, 'max_momentum': 0.9532274250059222, 'div_factor': 24.096469680886763, 'final_div_factor': 9230.387815492519}
LLH: 23731.1071
Timer: 17

Потомок:
Побед - 0
Data: {'batch_size': 132.48082128540432, 'history_days': 254.2466764357493, 'ticker_on': -6.464820434320231, 'day_of_year_on': 3.685802708698074, 'day_of_period_on': -2.620585467398418, 'prices_on': -2.337287969756517, 'dividends_on': 7.681354684677912, 'turnover_on': 25.040997218492926, 'average_turnover_on': -0.0698341664329086}
Model: {'start_bn': -0.5858115877491379, 'kernels': 8.633450136196913, 'sub_blocks': 1.308749066568089, 'gate_channels': 9.552349873715647, 'residual_channels': 8.847602575625233, 'skip_channels': 7.3096911302148, 'end_channels': 8.852240465245252}
Optimizer: {'betas': 0.9989993426843032, 'eps': 1.0060536103558416e-08, 'weight_decay': 0.010295120865148551, 'amsgrad': -6.134958355139449}
Scheduler: {'max_lr': 0.0076504540022160165, 'epochs': 1.007282921001843, 'pct_start': 0.29899929374666734, 'anneal_strategy': 2.6056870614103578, 'base_momentum': 0.8470992694037067, 'max_momentum': 0.947933968094696, 'div_factor': 24.6413928425561, 'final_div_factor': 10712.89526526514}
Количество слоев - 92
Количество параметров - 14689
Epochs - 1.01

**Comment by WLM1ke** [comment]
Вроде понял, где ошибка. Если эту модель не удаляли из базы, в документе модели измените дату на какую-нибудь существенно более раннюю, чем текущая и уберите из тикеров любой. При запуске эволюции это форсирует ее повторное обучение с нуля в первую очередь. По идее ошибка должна уйти.
