### ISSUE TITLE
[E:pyppeteer.connection] connection unexpectedly closed

### ISSUE THREAD

**Issue by RomaKoks** [WLM1ke/poptimizer#50]
`INFO:Mapper:Сохранение ID(package='data', group='quotes', name='KOGK')
INFO:Mapper:Сохранение ID(package='data', group='quotes', name='WMT-RM')
INFO:Mapper:Сохранение ID(package='data', group='quotes', name='VTRS-RM')
INFO:Mapper:Сохранение ID(package='data', group='quotes', name='VZRZ')
[E:pyppeteer.connection] connection unexpectedly closed
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-4231' coro=<Connection._async_send() done, defined at /home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/pyppeteer/connection.py:69> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/pyppeteer/connection.py", line 73, in _async_send
    await self.connection.send(msg)
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/pyppeteer/connection.py", line 79, in _async_send
    await self.dispose()
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/pyppeteer/connection.py", line 170, in dispose
    await self._on_close()
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/pyppeteer/connection.py", line 151, in _on_close
    cb.set_exception(_rewriteError(
asyncio.exceptions.InvalidStateError: invalid state
`

**Comment by WLM1ke** [comment]
В отъезде до конца недели — вернусь посмотрю.

**Comment by RomaKoks** [comment]
Ок, еще есть такой:
`Forecasts: 73it [00:55,  1.32it/s]
Traceback (most recent call last):
  File "/home/UNAME/PycharmProjects/poptimizer/loop.py", line 13, in <module>
    optimize(date)
  File "/home/UNAME/PycharmProjects/poptimizer/poptimizer/__main__.py", line 30, in optimize
    opt = Optimizer(port)
  File "/home/UNAME/PycharmProjects/poptimizer/poptimizer/portfolio/optimizer.py", line 37, in __init__
    self._metrics = metrics.MetricsResample(portfolio)
  File "/home/UNAME/PycharmProjects/poptimizer/poptimizer/portfolio/metrics.py", line 138, in __init__
    for forecast in evolve.get_forecasts(tickers, date):
  File "/home/UNAME/PycharmProjects/poptimizer/poptimizer/evolve/forecaster.py", line 69, in get_forecasts
    forecasts = Forecasts(tickers, date)
  File "/home/UNAME/PycharmProjects/poptimizer/poptimizer/evolve/forecaster.py", line 29, in __init__
    forecast = organism.forecast(tickers, date)
  File "/home/UNAME/PycharmProjects/poptimizer/poptimizer/evolve/population.py", line 124, in forecast
    forecast = model.forecast()
  File "/home/UNAME/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 267, in forecast
    model = self.get_model(loader, False)
  File "/home/UNAME/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 160, in get_model
    self._model = self._load_trained_model(pickled_model, loader, verbose)
  File "/home/UNAME/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 176, in _load_trained_model
    model.load_state_dict(state_dict)
  File "/home/UNAME/anaconda3/envs/finan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for WaveNet:
	size mismatch for bn.weight: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for bn.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for bn.running_mean: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for bn.running_var: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for start_conv.weight: copying a param with shape torch.Size([4, 3, 1]) from checkpoint, the shape in current model is torch.Size([4, 2, 1]).`

**Comment by RomaKoks** [comment]
Попытался дропнуть базу и прогнать все с нуля:
1й запуск:
https://gist.github.com/RomaKoks/639a8d8a4fc8a9f27d67a115f1fa7db6
2й запуск:
https://gist.github.com/RomaKoks/d0618fd41b195fa4fdcd908edc09847a

**Comment by WLM1ke** [comment]
Я вернулся, запустил и у меня тоже упало.

Во-первых, поменялся дизайн одного сайта - пришлось скорректировать парсер.
Во-вторых, похоже в библиотеке pyppeteer был небольшой баг с закрытием headless браузера - я обновил ее до последней версии.

После этого заработало.

**Comment by RomaKoks** [comment]
Обновил pyppeteer до 0.2.5 и репозиторий. Дропнул снова базу. Результат такой же:
> 1й запуск:
> https://gist.github.com/RomaKoks/639a8d8a4fc8a9f27d67a115f1fa7db6
> 2й запуск:
> https://gist.github.com/RomaKoks/d0618fd41b195fa4fdcd908edc09847a
=(

**Comment by WLM1ke** [comment]
Не очень понятно, что вы конкретно запускаете?

**Comment by RomaKoks** [comment]
Я случайно забыл про 0й запуск:
https://gist.github.com/RomaKoks/24fca14227975759f7548e0e031bb9f6
А после уже идут 1й и 2й.
Я запускаю:
https://gist.github.com/RomaKoks/de06fcb821c279f21e566de0cc5fad8b

**Comment by WLM1ke** [comment]
Давайте по шагам действовать. Пока остановимся на самом первоначальном запуске с пустой базой. 

Ваш скрипт содержит достаточно много if-ов в привязке в времени, поэтому может немного по разному исполняться, в том числе сначала запустить optimize и только потом запустить evolve, что неизбежно приведет к ошибке, так как не будет обученных моделей. Я предлагаю снести базу и для эксперимента упростить скрипт до такого:

`
from poptimizer.__main__ import evolve, optimize
from poptimizer.data.views.moex import last_history_date

if __name__ == '__main__':
    date = last_history_date()
    evolve()
    optimize(date)
`

**Comment by RomaKoks** [comment]
Результат аналогичен 0му запуску: https://gist.github.com/RomaKoks/b6be962c7404718aa1f742c0040f9063

**Comment by WLM1ke** [comment]
А такой вопрос - вы как стёрли базу и сам процесс MongoDB  завершали?

**Comment by RomaKoks** [comment]
Процесс MongoDB не завершал. Базу стер из Mongo Compas удалив коллекции data и source

**Comment by WLM1ke** [comment]
Первый момент - когда программа висит, на самом деле она качает первоначальные данные. У меня этот процесс занимает около минуты. Может на твоем компе какие-то проблемы с соединением, и он идет дольше.  Чтобы видеть, что программа не зависла, а процесс идет лучше активировать логер - будет видно чего он качает и сохраняет в базу. Я запускал таким образом:


`
import logging

logging.basicConfig(level=logging.INFO)

from poptimizer.__main__ import evolve, optimize
from poptimizer.data.views.moex import last_history_date

if __name__ == '__main__':
    date = last_history_date()
    evolve()
    optimize(date)
`

Второй момент - после добавления ряда бумаг стартовые условия эволюции не совсем удачные. Я изменил в последней версии.

**Comment by RomaKoks** [comment]
Процесс загрузки дданных доходит до строк:
```
INFO:BCSGateway:GEMA
INFO:BCSGateway:MGNT
INFO:Mapper:Сохранение ID(package='data', group='div_ext', name='MGNT')
INFO:Mapper:Сохранение ID(package='data', group='div_ext', name='GEMA')
```
меньше чем за минуту, после зависает.

https://gist.github.com/RomaKoks/2816e04a4a269c444fba209b9a9811b4

**Comment by WLM1ke** [comment]
Странно это все - у меня локально и на тестовом сервере GitHub все проходит. 

Есть подозрение, что у вас состав портфеля отличается от дефолтного, и какая-то дополнительная бумага глюки порождает. Попробуйте запустить с дефолтным перечнем тикеров.

**Comment by RomaKoks** [comment]
с дефолтными схожая ситуация https://gist.github.com/RomaKoks/f59e92ec011d1085e990f3e8a18464f0

**Comment by WLM1ke** [comment]
Я даже не знаю, как удаленно поймать проблему, которая у меня не воспроизводится. У меня самое большое подозрение, что возникает какая-то проблема с работай headless браузера.

Как вариант, предлагаю закомментить строку с загрузчиком с conomy.ru:

https://github.com/WLM1ke/poptimizer/blob/6c6ce57c1c349a07c0cfe4307db9831f5098f75d/poptimizer/data/domain/tables/dividends.py#L83

**Comment by RomaKoks** [comment]
Запускал и под linux (mint/ubuntu 20.04) и под windows - одно и то же. А почему conomy, если виснет на BCSGateway?

**Comment by WLM1ke** [comment]
Исполнение асинхронное, поэтому на чем конкретно виснет не понятно до конца. По опыту чаще всего проблемы бывали именно conomy, но можно каждый из трех по очереди отключить и посмотреть. 

Так же вариант, начать с метода:

https://github.com/WLM1ke/poptimizer/blob/6c6ce57c1c349a07c0cfe4307db9831f5098f75d/poptimizer/data/domain/tables/dividends.py#L60

Заменить весь код на return []

Тогда он вообще не будет порождать события для начала скачивания с этих сайтов.

**Comment by RomaKoks** [comment]
После комментирования conomy загрузка данных прошла, обучение прошло и почти прошел прогноз, но упал:
https://gist.github.com/RomaKoks/58da969d10fa75133b2dd10044037d15

**Comment by WLM1ke** [comment]
Про пустой портфель вы правы, судя по вашему логу. 

Про падение пайплайна - у меня просто такого не было, поэтому как-то особо эту ситуацию не продумывал. 
Понять бы почему и что конкретно у вас происходит, и почему у меня и на тестовом сервере GitHub все окей.

**Comment by WLM1ke** [comment]
Один из вариантов поменять строку:

https://github.com/WLM1ke/poptimizer/blob/1bb9e85e762c78e93c914f0e855371f74c24e886/poptimizer/data/adapters/gateways/conomy.py#L43

На self._browser = await pyppeteer.launch(autoClose=False, headless=False)

И посмотреть глазками, что в браузере происходит.

**Comment by WLM1ke** [comment]
Еще возможный вариант, что у вас канал наооборот гораздо быстрее моего, сайт защищается от DDoS и блокирует вас. В ту же строку можно попытаться slowMo=500 добавить, чтобы он раз в пол секунды пытался обращать.

**Comment by RomaKoks** [comment]
> И посмотреть глазками, что в браузере происходит.

https://yadi.sk/i/LVvJn3Jei5zXyA

> Есть подозрение, что у вас состав портфеля отличается от дефолтного, и какая-то дополнительная бумага глюки порождает. Попробуйте запустить с дефолтным перечнем тикеров.

Как можно быстро понять в каком из тикеров проблема? Проблемы с прогнозом действительно происходят после добавления тикеров, отсутствующих в начальном наборе. Проверять, добавляя по одному тикеру, очень долго - минимум час на то чтобы дойти до прогноза. Это может понадобиться больше суток.

**Comment by WLM1ke** [comment]
Посмотрел ролик - понятнее не стало. Не знаю, что там происходит. slowMo=500 тоже не помогает? Такое в впечатление, что только на одной вкладке все действия свершаются, а остальные остаются на паузе. 
Еще один вариант - у вас может быть хромиум какой-то очень старый, и pyppeteer с ним некорректно работает. Я не знаю, как это под линуксом проверить/обновить. 

По поводу тикера понять можно следующим образом:
Судя по тем ошибкам, которые вы публиковали у вас модели как буду-то учатся на тикерах, которые отличаются от тикеров в портфеле. Можно у обученной модели посмотреть ключ tickers и сопоставить его с вашим перечнем. Подозреваю, что там каких-то стикеров не будет. Потом можно глянуть чего с ними не так.

**Comment by WLM1ke** [comment]
Еще идея возникла по поводу фоновых страниц - закрывать отработавшие страницы.

Заменить строчку

https://github.com/WLM1ke/poptimizer/blob/1bb9e85e762c78e93c914f0e855371f74c24e886/poptimizer/data/adapters/gateways/conomy.py#L80

```
page_html =  cast(str, await page.content())
await page.close()
return page_html
```

**Comment by RomaKoks** [comment]
Спасибо, попробую. Еще странно, что даже после успешного завершения (после ручных манипуляций) браузер не закрылся. Это ожидаемое поведение?

**Comment by WLM1ke** [comment]
По идее он должен закрываться - за это отвечает строчка:

https://github.com/WLM1ke/poptimizer/blob/1bb9e85e762c78e93c914f0e855371f74c24e886/poptimizer/data/adapters/gateways/conomy.py#L44

Если ее нет то после каждого запуска множиться процессы Хроумиума в памяти. 

У меня они появляются во время работы, а потом исчезают - то есть закрытие происходит. 
Как вариант глянуть, что у вас там до запуска - прибить их все в ручную, а потом запустить. Может есть какой дефектный работающий процесс, который как-то запарывает все остальные.

**Comment by RomaKoks** [comment]
Посмотрел версию хромиума, он действительно старый (71.0.3542.0). Как его лучше обновить? С какой из библиотек он вообще пришел?

**Comment by WLM1ke** [comment]
Я думаю, если он старый, то его сама Ubuntu включает. В питоне с ним взаимодействует pyppeteer. 
В в нем есть комнда [pyppeteer-install](https://github.com/miyakogi/pyppeteer#usage) для установки, но я не уврен, что таким же образом можно обновить. 

Насколько я понимаю, в Ubuntu  apt update используется для обновления пакетов.

**Comment by RomaKoks** [comment]
Я запускал из windows последний раз. Кажется, pyppeteer его (хромиум) и принес с собой, но обновлять вместе с собой не стал. Попробую удалить pyppeteer чисткой кэша и установить заново.

**Comment by WLM1ke** [comment]
Я не уверен, что переустановка pyppeteer с нуля повлечет переустановку Chromium.

**Comment by RomaKoks** [comment]
удалил pyppeteer и его chromium, при запуске скрипта он скачал снова такой же chromium.

**Comment by WLM1ke** [comment]
Попробуйте код с закрытием страницы добавить, как выше написал. Потом попробуем более радикальное решение.

**Comment by RomaKoks** [comment]
Попробовал - все равно до ручного переключения на другие страницы ничего не происходит. После Переключения процесс идет далее окно браузера осталось.

**Comment by WLM1ke** [comment]
Тогда остается вариант это все принудительно завершать, если не получилось за определенное количество секунд. Вернуть к исходной версии и блок try/except :

https://github.com/WLM1ke/poptimizer/blob/1bb9e85e762c78e93c914f0e855371f74c24e886/poptimizer/data/adapters/gateways/conomy.py#L132

Заменить на:

```

try:
    html = await asyncio.wait_for(_get_html(ticker), timeout=30)
except (errors.TimeoutError, asyncio.TimeoutError):
    return pd.DataFrame(columns=[ticker])

```

**Comment by RomaKoks** [comment]
Прошло, но окно все равно осталось.

**Comment by RomaKoks** [comment]
>  у обученной модели посмотреть ключ tickers и сопоставить его с вашим перечнем. Подозреваю, что там каких-то тикеров не будет. Потом можно глянуть чего с ними не так.

Посмотрел у модели, которая прошла переоценку - список совпадает. Отличие от базового набора заключается в этих тикерах:
ASSB
BISV
BISVP
KBSB
KBTK
KRSB
KRSBP
LNZLP
MGTS
PMSB
RZSB
STSBP
TORSP

Что-то криминального я у них не заметил.

**Comment by WLM1ke** [comment]
> Прошло, но окно все равно осталось.

Добавлю, тогда в следующую версию это изменение. С закрытием браузера не знаю чего делать. Если вы хотя бы иногда перезагружаете компьютер, наверное в этом нет ничего особенно страшного. Но если есть идеи, как починить  готов поправить. 

> По поводу тикеров. 

Вы эволюцию когда запускаете, они добавлены в описание портфеля? 
Вбивали ли вы для них в базу дивиденды?

Есть одно подозрение - BISV. Не торгуется в 2005 года.

**Comment by RomaKoks** [comment]
> Вы эволюцию когда запускаете, они добавлены в описание портфеля?

да

> Вбивали ли вы для них в базу дивиденды?

нет


> Есть одно подозрение - BISV. Не торгуется в 2015 года.

Точно, попробую без него, спасибо)

**Comment by RomaKoks** [comment]
> asyncio.TimeoutError):

только тут нужен asyncio.exceptions.TimeoutError

**Comment by WLM1ke** [comment]
Вроде в примерах [asyncio.TimeoutError](https://docs.python.org/3/library/asyncio-task.html#timeouts) - насколько понимаю asyncio.exceptions.TimeoutError импортирован в asyncio, поэтому доступен, как asyncio.TimeoutError

**Comment by RomaKoks** [comment]
В таком виде он не ловился.

**Comment by WLM1ke** [comment]
Странно это очень - залил версию с asyncio.exceptions.TimeoutError
