### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by RomaKoks** [WLM1ke/poptimizer#55]
Попробовал обновиться

***2021-05-07: Шаг эволюции — 1***
LLH - (-, -, -)
Максимум побед - None
Фактор - 100.00%
Переоцениваю родителя:
Побед — 0
Data: {'batch_size': 128.2320698209353, 'history_days': 77.63810095882658, 'ticker_on': 0.7109999601234973, 'day_of_year_on': 0.8938235704831489, 'day_of_period_on': -0.7415209704374337, 'prices_on': 0.3792032610427596, 'dividends_on': 0.7597968132102717, 'turnover_on': 0.5860555137690139, 'average_turnover_on': 0.6750234817940721, 'rvi_on': -0.758365200271929, 'mcftrr_on': -0.7678090475533608, 'imoex_on': -0.5441796726478852, 'ticker_type_on': -0.09997730965326945, 'usd_on': -0.334036922316718, 'open_on': -0.27818249383845906}
Model: {}
Optimizer: {'betas': 0.9990053414863606, 'eps': 9.991434975458438e-09, 'weight_decay': 0.009998127788332577}
Scheduler: {'max_lr': 0.009314820871952526, 'epochs': 1.0009126725233755, 'pct_start': 0.30099817073495205, 'anneal_strategy': 0.9825538484814915, 'base_momentum': 0.8492757678903675, 'max_momentum': 0.9508768810821049, 'div_factor': 24.975410927815844, 'final_div_factor': 10006.218260928737}
Traceback (most recent call last):
  File "path_to\poptimizer\poptimizer\__main__.py", line 19, in evolve
    ev.evolve(port)
  File "path_to\poptimizer\poptimizer\evolve\evolve.py", line 56, in evolve
    if _eval_and_print(parent, tickers, end) is None:
  File "path_to\poptimizer\poptimizer\evolve\evolve.py", line 98, in _eval_and_print
    fitness = organism.evaluate_fitness(tickers, end)
  File "path_to\poptimizer\poptimizer\evolve\population.py", line 78, in evaluate_fitness
    llh = model.llh
  File "path_to\poptimizer\poptimizer\dl\model.py", line 111, in llh
    self._llh = self._eval_llh()
  File "path_to\poptimizer\poptimizer\dl\model.py", line 145, in _eval_llh
    model = self.prepare_model(loader)
  File "path_to\poptimizer\poptimizer\dl\model.py", line 123, in prepare_model
    self._model = self._train_model()
  File "path_to\poptimizer\poptimizer\dl\model.py", line 218, in _train_model
    model = self._make_untrained_model(loader)
  File "path_to\poptimizer\poptimizer\dl\model.py", line 192, in _make_untrained_model
    model = model_type(loader.history_days, loader.features_description, **self._phenotype["model"])
KeyError: 'model'

https://github.com/WLM1ke/poptimizer/blob/29d901067024b57111b13ac3a5750c0f09fae7a6/poptimizer/dl/model.py#L192

Удаление моделей не изменило ситуацию.

В **self._phenotype** лежит вот что:
```
{
  'type': 'WaveNet',
  'data': {
    'features': {
      'Label': {
        'on': True
      },
      'Ticker': {
        'on': True
      },
      'DayOfYear': {
        'on': True
      },
      'DayOfPeriod': {
        'on': False
      },
      'Prices': {
        'on': True
      },
      'Dividends': {
        'on': True
      },
      'Turnover': {
        'on': True
      },
      'AverageTurnover': {
        'on': True
      },
      'RVI': {
        'on': False
      },
      'MCFTRR': {
        'on': False
      },
      'IMOEX': {
        'on': False
      },
      'TickerType': {
        'on': False
      },
      'USD': {
        'on': False
      },
      'Open': {
        'on': False
      }
    },
    'batch_size': 128,
    'history_days': 77
  },
  'optimizer': {
    'betas': (0.9,
    0.9990053414863606),
    'eps': 9.991434975458438e-09,
    'weight_decay': 0.009998127788332577
  },
  'scheduler': {
    'max_lr': 0.009314820871952526,
    'epochs': 1.0009126725233755,
    'pct_start': 0.30099817073495205,
    'anneal_strategy': 'cos',
    'base_momentum': 0.8492757678903675,
    'max_momentum': 0.9508768810821049,
    'div_factor': 24.975410927815844,
    'final_div_factor': 10006.218260928737
  }
}

```

**Comment by WLM1ke** [comment]
Запушил исправление
