### ISSUE TITLE
AttributeError. (doc has no attribute genotype)

### ISSUE THREAD

**Issue by RomaKoks** [WLM1ke/poptimizer#59]
Довольно регулярно вылетает такая ошибка (вероятно, в результате некорректного завершения работы) и приходится искать модель без генотипа. Предлагаю внести маленькое изменение:
поместить этот print
https://github.com/WLM1ke/poptimizer/blob/197f39f980782348ca1fcfb2d0d00ac95cf68316/poptimizer/evolve/evolve.py#L102
в try строчкой ниже и ловить 
`(ModelError, AttributeError)`

**Comment by WLM1ke** [comment]
ОК - поправлю чуть позже
