### ISSUE TITLE
MAX_HISTORY неопределён при пустой базе

### ISSUE THREAD

**Issue by RomaKoks** [WLM1ke/poptimizer#64]
https://github.com/WLM1ke/poptimizer/blob/13d327be73bafa61ee73c94b6f05185ac40cf3c9/poptimizer/portfolio/portfolio.py#L32

При пустой базе падает на этом месте, возможно, её тоже нужно поместить в try.
лог:
https://gist.github.com/RomaKoks/d7cf5a03bf58a1315af1f3fed4662c4b#file-max_history-error-log

**Comment by WLM1ke** [comment]
Спасибо. Поправлю.
