### ISSUE TITLE
VEON-RX тип акции

### ISSUE THREAD

**Issue by AlexQww** [WLM1ke/poptimizer#78]
https://github.com/WLM1ke/poptimizer/blob/defb9db0202a5561254fc638ff36077b76456cb1/poptimizer/data/domain/tables/securities.py#L25-L26

Видимо, с появлением VEON-RX тут стоит модифицировать условие на проверку типа акции, иначе загрузка данных упадет сегодня ночью.

**Comment by WLM1ke** [comment]
Подумаю, как лучше поступить. 
Пока можно raise WrongTickerTypeError(ticker) на return col.ORDINARY заменить.
