### ISSUE TITLE
При ротации логов падает с ошибкой "Permission denied" если имя пользователя содержит <точку>

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#87]
Доброго дня!
Система OSX, логин пользователя в системе с точкой <имя>.<фамилия>  
Приложение запущено из домашнего каталога /Users/<имя>.<фамилия>/poptimazer/
При ротации логов, в функции "namer" /poptimizer/poptimizer/shared/log.py  из-за "split(".")" получаю следующее расположение для файла с бэкапом '/Users/<имя>_2021-12-07_18-00-34_610884.log' и соответственно ошибку "Permission denied"

Замена 
`name = default_name.split(".")[0]`

на 
`name = default_name.split(".log")[0]`

исправило ситуацию

**Comment by WLM1ke** [comment]
Спасибо. Исправлю.
