### ISSUE TITLE
Ограничить максимальное кол-во эпох настройкой может быть ?

### ISSUE THREAD

**Issue by Questtt** [WLM1ke/poptimizer#88]
DateCheckRequired(timestamp=datetime.datetime(2021, 12, 7, 20, 31, 47, 843809))
***2021-12-06: Шаг эволюции — 214***
LLH - (-2.2139, 2.2601, 2.4676)
RET - (-0.7104, 0.4548, 4.0908)
Организмов - 211 / Максимум оценок - 21
Доля принятых - 36.69%

Родитель:
LLH — 1.6468:  1.7021,  1.6963,  1.6906,  1.6870,  1.6750,  1.6597,  1.6637,  1.6427,  1.6464,  1.6546,  1.6557,  1.6473,  1.6450,  1.6418,  1.6266,  1.6362,  1.6305,  1.6292,  1.6254,  1.6308
RET — -0.1679: -0.5417, -0.5741, -0.5027, -0.4789, -0.4114, -0.2440, -0.2873, -0.1028, -0.1737, -0.2066, -0.3161, -0.1621, -0.0832,  0.0163,  0.1652,  0.0561,  0.0891,  0.1086,  0.1810,  0.0807
Timer — 0:30:35 / Scores - 20
Data: {'batch_size': 7095.271077633346, 'history_days': 104.2664946854577, 'ticker_on': 4976.2716520817985, 'day_of_year_on': -3.709624878883848, 'day_of_period_on': 137.4568151927667, 'prices_on': -16.121645323896313, 'dividends_on': -4605.032017093387, 'turnover_on': 78727.19365161215, 'average_turnover_on': 2126.666392327704, 'rvi_on': -57826.07390087617, 'mcftrr_on': -1739.7378353702825, 'imoex_on': 460.7037304850061, 'ticker_type_on': 383706.00156781333, 'usd_on': 202413.2533475839, 'open_on': 47.910467251496684, 'high_on': -569.0460289604246, 'low_on': 4.311145782034553, 'meogtrr_on': -67.47850617523062}
Model: {'start_bn': 8.526469978101927, 'kernels': 27.67607274460994, 'sub_blocks': 11.077653647532772, 'gate_channels': 7.36760712976323, 'residual_channels': 5.830611696867351, 'skip_channels': 175.2040654474389, 'end_channels': 129.06367751044317, 'mixture_size': 406.9241719003154}
Optimizer: {'betas': 0.9512142169103824, 'eps': 0.000124510967630482, 'weight_decay': 13.612907456891998}
Scheduler: {'max_lr': 0.0499352822631719, 'epochs': 3.6580907291933498, 'pct_start': 0.820676400666021, 'anneal_strategy': -3730.263470910985, 'base_momentum': 0.9972310235283417, 'max_momentum': 0.9201040129780192, 'div_factor': 1430.0763899622098, 'final_div_factor': 1573377.7010648176}

Претендент - новый организм:
LLH — -
RET — -
Timer — 0:00:00 / Scores - 0
Data: {'batch_size': 6895.328881408579, 'history_days': 112.0798316286424, 'ticker_on': 4478.858597534277, 'day_of_year_on': -3.8270234650609622, 'day_of_period_on': 159.05112347948247, 'prices_on': -217.4771456933069, 'dividends_on': 7007.702613656215, 'turnover_on': 71872.51718327151, 'average_turnover_on': 1227.43596951955, 'rvi_on': 380738.18073469825, 'mcftrr_on': -1722.3528881635725, 'imoex_on': 392.29323879244976, 'ticker_type_on': 194817.4720718744, 'usd_on': 146121.75177522193, 'open_on': 43.19711628339914, 'high_on': -550.3772067225993, 'low_on': 5.6694529090453925, 'meogtrr_on': -115.39740648167755}
Model: {'start_bn': 2.1897676303046563, 'kernels': 26.807849195937457, 'sub_blocks': 11.080826090600356, 'gate_channels': 9.482139014483748, 'residual_channels': 5.022165621453517, 'skip_channels': 200.0585995947543, 'end_channels': 381.17119402983553, 'mixture_size': 376.6544359345419}
Optimizer: {'betas': 0.9373288828589553, 'eps': 0.00014087801919633505, 'weight_decay': 129.54538277095145}
Scheduler: {'max_lr': 0.049719869950901545, 'epochs': 9650.153309416133, 'pct_start': 0.832731169529873, 'anneal_strategy': -2578.2779830306904, 'base_momentum': 0.9677651595266519, 'max_momentum': 0.9208398561827363, 'div_factor': 39353.97274675947, 'final_div_factor': 1499376.0759575109}

DateCheckRequired(timestamp=datetime.datetime(2021, 12, 7, 20, 31, 47, 910822))
Epochs - 9650.15 / Train size - 215015
Количество слоев / параметров - 435 / 704524

--
~~> Train:   0%|          | 1/308805 [00:18<1587:17:08, 18.50s/it, 0.86492]

т.е. ориентировочное время проверки данного организма 1587/24 = 66 дней, за 6.5 часов даже 1 % тренировки не прошло.
Можно ли как-то ограничить максимальное кол-во эпох ? Наверняка такое кол-во эпох слишком избыточно

**Comment by WLM1ke** [comment]
Подумаю, как это лучше сделать. Пока легче грохнуть процесс и запустить заново.

**Comment by Questtt** [comment]
> Подумаю, как это лучше сделать. Пока легче грохнуть процесс и запустить заново.

Ага, так и сделал. Было бы обидно, если бы отработало 66 дней и организм бы умер)
