### ISSUE TITLE
Популяция вымерает

### ISSUE THREAD

**Issue by swpman** [WLM1ke/poptimizer#89]
Вымерла популяция моделей до 10 шт. Поднял из резервной копии базу с обученными моделями за 18 ноября, модели 256 обучились на данных с 19.11 до 08.12. Сегодня ночью на тестах данных от 09.12 опять популяция сократилась до 13. Запустил сегодня с нуля эволюцию на 28м шаге из 100 начальных осталось 83.
Куда копать?

**Comment by WLM1ke** [comment]
В текущей реализации, так и должно быть.

**Comment by swpman** [comment]
можно ли доверять оптимизации на оставшихся выживших 10?

**Comment by WLM1ke** [comment]
Думаю нельзя. К сожалению простого решения сейчас нет. Можно подождать пока популяция подрастет. Мне текущий вариант не сильно нравится, думаю как его немного поправить, но готовой версии пока нет.

**Comment by swpman** [comment]
Спасибо, откатил все обратно, посмотрю как будет меняться популяция .
