### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by ErQrYfkrju** [WLM1ke/poptimizer#92]
Здравствуйте!
Тоже решил познакомится с вашим решением.
Собрал ваше приложение в контейнере и запустил evolve
Загрузку дивидентов прошла успешно. А дальше вылезло вот это....
Корректность работы pyppeteer проверил.
```
python3.9 -m poptimizer evolve
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/app/poptimizer/__main__.py", line 46, in <module>
    app(prog_name="poptimizer")
  File "/usr/local/lib/python3.9/dist-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/app/poptimizer/__main__.py", line 17, in evolve
    ev.evolve()
  File "/opt/app/poptimizer/evolve/evolve.py", line 54, in evolve
    step, current = self._step_setup(step, current)
  File "/opt/app/poptimizer/evolve/evolve.py", line 85, in _step_setup
    self._end = dates[1]
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/extension.py", line 279, in __getitem__
    result = self._data[key]
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/arrays/datetimelike.py", line 322, in __getitem__
    result = super().__getitem__(key)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/arrays/_mixins.py", line 194, in __getitem__
    result = self._ndarray[key]
IndexError: index 1 is out of bounds for axis 0 with size 0
```

**Comment by WLM1ke** [comment]
Попробуйте скачать последнюю версию - в пятницу был необычный день, когда торговались только иностранные бумаги. В последней версии по идее должно работать корректно.

**Comment by ErQrYfkrju** [comment]
загрузил из master
результат тот же, если вывести на экран len(dates) он нулевой....
я сделал самый простой setup.py для установки пакета
```
from setuptools import setup, find_packages
setup(
    name="poptimizer",
    version="1.0",
    packages=find_packages(),
    entry_points={
        'console_scripts': ['app=app.app:main', ]    
    },
)
```
может накосячил где...

**Comment by WLM1ke** [comment]
Вы загрузили из мастера после моего ответа и перестояли свои контейнеры? Я просто докинул немного коммитов после вашего сообщения об ошибке.

**Comment by ErQrYfkrju** [comment]
Да из master выкачал и пересобрал
```
commit 18756e8bdbfcac3ebd7ba241f86b25bcb27cc22f (HEAD -> master, origin/master, origin/HEAD)
Author: WLM1ke <wlmike@gmail.com>
Date:   Sun Jan 9 13:53:06 2022 +0300

    feat: правило рассылки регулярного сообщения
```

**Comment by WLM1ke** [comment]
Сложно понять дистанционно в чем проблема. Я попробовал запустить с нуля - у меня ошибка не выпадает, но я запускаю без контейнеров и setup.py. 

Может вам тоже попытаться для начала запустить локально напрямую. Выкачать в папочку проекта, создать виртуальное окружение в корне проекта и простой файлик для запука:

`from poptimizer.evolve.evolve import Evolution

if __name__ == "__main__":
    Evolution().evolve()`

**Comment by ErQrYfkrju** [comment]
Сейчас буду пробовать

**Comment by ErQrYfkrju** [comment]
Да всё тоже самоё....
```
python3.9 -m venv .venv
source .venv/bin/activate
pip3.9 install -r requirements.txt
python3.9 -m poptimizer evolve
```
Загружаются данные и вылетает в том же самом месте

**Comment by WLM1ke** [comment]
Хорошо, что про портфель написали. Во-первых, это все бессмысленно на трех бумагах - не достаточно данных для обучения сетей. Во-вторых, при таком наборе бумаг вылезает редкий баг - не уверен, что его имеет смысл править, но в общем нужна хотя бы одна иностранная бумага из-за кривого торгового дня в пятницу или ждать завтрашнего дня когда появятся котировки за понедельник.

**Comment by ErQrYfkrju** [comment]
Ну я сначала на base.yml из master запускал, но он с нулями не знаю имеет это значение или нет...
Потом почему сейчас грузятся только за предыдущий торговый день... есть ли какая то возможность загрузить больший срок?

**Comment by WLM1ke** [comment]
>Ну я сначала на base.yml из master запускал, но он с нулями не знаю имеет это значение или нет...

Для эволюции количество бумаг не имеет значения - важен их перечень, на котором будет идти обучение. 

>Можно ли как то в mongodb загрузить историю за последние 3-5 лет, чтобы потом её как то просмотреть?

Грузится вся история до последнего полного тортового дня включительно, используется история с 2015 года. 

PS: Утром оказалось, что баг более серьезным, чем я думал, поэтому буду править.

**Comment by ErQrYfkrju** [comment]
плохо что серьезный, хорошо что локализовался. пока запустил обучение...
можно как то из имеющихся данных в базе получить df как у yfinance для перечня тикеров?

**Comment by WLM1ke** [comment]
Я не знаю, как там у yfinance. Есть функци для получения перечня всех бумаг по которым скачиваются котировки 
https://github.com/WLM1ke/poptimizer/blob/18756e8bdbfcac3ebd7ba241f86b25bcb27cc22f/poptimizer/data/views/listing.py#L44

В файле все бумаги, по которым я обновляю дивиденды https://github.com/WLM1ke/poptimizer/blob/master/portfolio/base.yaml

**Comment by ErQrYfkrju** [comment]
https://habr.com/ru/post/561980/
вот по этой статье пробовал строить тестовый портфель, там данные скачиваются с yahoo finance каждый раз. у вас скачаны данные и уже локально доступны для тестовых запросов к ним

**Comment by WLM1ke** [comment]
Если каждый раз дергать MOEX, то вас быстро заблокируют. 
Данные скачиваются полностью при первом запуске и инкрементальной обновляются каждый день.

**Comment by ErQrYfkrju** [comment]
я немного про другое,как с помощью имеющихся уже данных собрать входные данные для указанных в статье методов. там скачивание исторических данных идёт с yahoo, для moex добавляя .ME к тикеру.

**Comment by WLM1ke** [comment]
Для получения цен 
https://github.com/WLM1ke/poptimizer/blob/18756e8bdbfcac3ebd7ba241f86b25bcb27cc22f/poptimizer/data/views/quotes.py#L38
Для получения цен и дивидендов
https://github.com/WLM1ke/poptimizer/blob/18756e8bdbfcac3ebd7ba241f86b25bcb27cc22f/poptimizer/data/views/quotes.py#L87

**Comment by ErQrYfkrju** [comment]
вечером посмотрю и сравню результаты...

**Comment by ErQrYfkrju** [comment]
https://github.com/WLM1ke/poptimizer/pull/93
Поставил на обучение
