### ISSUE TITLE
Оптимизация портфеля в течение дня

### ISSUE THREAD

**Issue by ArjaraGit** [WLM1ke/poptimizer#96]
Добрый день
Подскажите пожалуйста: метод optimize, выдающий рекомендации - его следует запускать несколько раз в течение дня до тех пор пока он не покажет что оптимизировать больше нечего? или один раз в день?
т.е.:
- запустил в первый раз за день. оптимизатор выдал рекомендации на день. выполнил их, занес изменения в ямль 
- запустил после этого повторно, выполнил рекомендации
и так несколько раз за день?

**Comment by WLM1ke** [comment]
Оптимизатор использует линейную аппроксимацию для построения рекомендаций. Предполагается, что вы должны совершать небольшие сделки (~1% от стоимости портфеля), потом повторно запускать оптимизатор для уточнения рекомендаций и т.д. пока не останется рекомендаций на продажу. Останется одна рекомендация (PENDING) - это лучшая рекомендация на покупку, чтобы было ясно, куда тратить кэш, если он остался или внесен на счет.

**Comment by Questtt** [comment]
@WLM1ke я правильно понимаю, что совершать небольшие сделки(~1% от стоимости портфеля) в течение дня до тех пор пока не появится рекомендация (PENDING) ?
Т.е. по сути до тех пор, пока портфель не оптимизируется ?

**Comment by WLM1ke** [comment]
@Questtt да. Какой-то критической необходимости сделать все за один день нет. Обычно похожие рекомендации по оптимизации сохраняются достаточно долго, и их вполне можно осуществлять в течении нескольких дней.

**Comment by ArjaraGit** [comment]
@WLM1ke , спасибо
подскажите еще один момент: оптимизатор hmean отображает стоимость лота LOT_price.
вы как то ориентируетесь на них? например, выставляете заявки на покупку/продажу по указанной оптимизатором цене. 
или торгуете по текущим ценам?

**Comment by WLM1ke** [comment]
@ArjaraGit это не мой код, я в нем не ориентируюсь. Pull request реализовал @RomaKoks для своих целей - я замерджил, так как переключение на него стоит под настройками, но в деталях я не ориентируюсь, как его он использует

**Comment by RomaKoks** [comment]
@ArjaraGit LOT_price - цена лота на последний день (в базе) она не расчетная, соответственно это не рекомендация, а слегка устаревший факт.

**Comment by ArjaraGit** [comment]
@RomaKoks, спасибо. 
Не понял про "Модели используют суточные данные, они будут выдавать одинаковый результат в течение всего дня"
Если не менять ничего в ямль файлах с количеством бумаг, то - да, повторный запуск покажет те же рекомендации.
Но если выполнить рекомендации по hmean (купить продать указанное количество) и внести изменения по счету в ямль, то повторный запуск оптимизатора покажет новые рекомендации

@WLM1ke, оптимизатор resample - если оптимизатор рекомендует продавать бумагу - вы просто продаете все имеющееся количество? или какой-то процент (какой - решаете для себя сами)?
Рекомендации покупать, соответственно, на какой-то процент от свободных средств.
я ведь правильно понимаю?

**Comment by RomaKoks** [comment]
@ArjaraGit да, но вы можете запустить его один раз, просто изменив дефолтные параметры. Грубо говоря, он "перезапускается" сам ~10 раз по дефолту, вы можете изменить этот дефолт путем увеличения или уменьшения порогов на оборот.

**Comment by ArjaraGit** [comment]
@RomaKoks, теперь понял, спасибо

**Comment by WLM1ke** [comment]
@ArjaraGit 

Так как рекомендации строятся на основе линейного приближения и меняются по мере изменения позиций, в общем случае рекомендую совершать сделки маленькими порциями (порядка 1% от портфеля) и действуйте дальше с учетом уточненного прогноза.

Если у вас на счет по каким-то причинам много кэша (много внесли или случайно продали на большую сумму) сначала покупайте маленькими порциями, пока не снизите его количество.

После этого продавайте маленькими порциями и покупайте на полученные деньги.

**Comment by ArjaraGit** [comment]
@WLM1ke, спасибо
