### ISSUE TITLE
Не запускается evolve после ночного обновления данных

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#98]
Не запускается evolve после ночного обновления данных. Перезагрузка компьютера не помогла.

(base) usr@macbookpro poptimizer % python3 -m poptimizer evolve
{'P_VALUE': 0.05, 'FORECAST_DAYS': 21, 'HISTORY_DAYS_MIN': 63, 'TARGET_POPULATION': 100, 'START_EVOLVE_HOUR': 1, 'STOP_EVOLVE_HOUR': 1, 'COSTS': 0.025, 'MARKET_IMPACT_FACTOR': 1, 'OPTIMIZER': 'hmean'}
DateCheckRequired(timestamp=datetime.datetime(2022, 1, 21, 7, 42, 54, 441795))
DateCheckRequired(timestamp=datetime.datetime(2022, 1, 21, 7, 42, 54, 857282))
***2022-01-20: Шаг эволюции — 1***
LLH - (2.2584, 2.5542, 2.6298)
RET - (-0.3664, 0.1511, 1.4129)
Организмов - 315 / Максимум оценок - 47 / Поколений - 46
Scale - 100.00% / Jump - 100.00%

Родитель:
LLH —  2.3963:  2.3901,  2.6493,  2.6055,  2.5613,  2.5048,  2.7029,  2.7147,  2.6704,  2.6321,  2.5576,  2.6209,  2.5343,  2.4712,  2.5926,  2.6181,  2.3990,  2.5223,  2.5368,  2.5439,  2.2595,  2.3036,  2.2998,  1.8157,  1.6775,  1.6825,  2.2263,  2.0741,  2.2370,  2.3936,  2.1730,  2.2580,  2.4198,  2.2640,  2.2981,  2.3188,  2.0094,  2.2812,  2.3129,  2.4277,  2.1300,  2.2505,  2.3495,  2.5247,  2.4868
RET —  0.2492: -0.7723, -0.4505, -0.4916,  0.6591,  0.9796, -0.3230,  0.1437, -0.6328,  1.3425,  0.4985,  0.8764, -0.2682, -0.5779,  0.2591,  0.4496, -0.3588, -0.1654,  0.0780,  0.2898, -0.2750,  0.1712, -0.6531, -0.1056, -1.0902, -0.2169, -0.3889, -0.5889,  0.1422,  0.8783,  0.0086,  1.3413,  1.4211,  1.2323,  1.1356,  1.2360,  0.2829,  0.2394,  1.7225,  1.2317,  1.1361,  2.2526,  1.4470,  2.1715,  1.9925
Timer — 0:00:49 / Scores - 44
Data: {'batch_size': 134.93720982008335, 'history_days': 95.15098732309566, 'ticker_on': 0.278420801448794, 'day_of_year_on': 1.1551116675663693, 'day_of_period_on': 1.407492925322691, 'prices_on': -1.773827611186878, 'dividends_on': 0.014815914938429209, 'turnover_on': -5.916029228275023, 'average_turnover_on': 2.5581540279669333, 'rvi_on': 4.121499840929927, 'mcftrr_on': 0.5684369411017152, 'imoex_on': 0.2905145279785871, 'ticker_type_on': 0.6350888402315884, 'usd_on': -0.49814312990177595, 'open_on': 2.186429049519103, 'high_on': 7.9216789403768875, 'low_on': 923.4768231918068, 'meogtrr_on': -0.863917323297819}
Model: {'start_bn': 0.9910986626592879, 'kernels': 6.515293278016405, 'sub_blocks': 1.824447247226041, 'gate_channels': 4.39506695664396, 'residual_channels': 5.4473180230707285, 'skip_channels': 13.305460075664165, 'end_channels': 15.178670905203244, 'mixture_size': 3.878975632979092}
Optimizer: {'betas': 0.9989941493992441, 'eps': 1.9611817594831026e-08, 'weight_decay': 0.00041400063415165337}
Scheduler: {'max_lr': 0.0037451630007245304, 'epochs': 0.2425709289463799, 'pct_start': 0.30574198650894757, 'anneal_strategy': 0.6214439018017496, 'base_momentum': 0.8484705644342704, 'max_momentum': 0.9500814644420272, 'div_factor': 136.75930600312077, 'final_div_factor': 76869.10327725377}
Utility: {'risk_aversion': 0.9999993419164337, 'error_tolerance': 7.944409623215222e-07}

~~> Test: 100%|█████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 21.61it/s, 2.48251]
RET = -24.25% / MEAN = -12.61% / PLAN = 33.23% / STD = 17.41% / DD = 9.13% / POS = 5 / MAX = 34.61%
LLH worst difference: median - -0.0382, upper - -0.0049, max - 0.0656
RET worst difference: median - -0.4175, upper - 0.2462, max - 0.9418
Traceback (most recent call last):
  File "/Users/usr/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/usr/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/usr/poptimizer/poptimizer/__main__.py", line 46, in <module>
    app(prog_name="poptimizer")
  File "/Users/usr/.local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/usr/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/usr/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/usr/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/usr/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/usr/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/usr/.local/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/usr/poptimizer/poptimizer/__main__.py", line 17, in evolve
    ev.evolve()
  File "/Users/usr/poptimizer/poptimizer/evolve/evolve.py", line 64, in evolve
    current = self._step(current)
  File "/Users/usr/poptimizer/poptimizer/evolve/evolve.py", line 117, in _step
    if (hunter_margin := self._eval_organism(hunter)) is None:
  File "/Users/usr/poptimizer/poptimizer/evolve/evolve.py", line 183, in _eval_organism
    return self._get_margin(organism)
  File "/Users/usr/poptimizer/poptimizer/evolve/evolve.py", line 215, in _get_margin
    time_delta = _time_delta(org)
  File "/Users/usr/poptimizer/poptimizer/evolve/evolve.py", line 228, in _time_delta
    max_timer = max(doc["timer"] for doc in population.base_pop_metrics())
  File "/Users/usr/poptimizer/poptimizer/evolve/evolve.py", line 228, in <genexpr>
    max_timer = max(doc["timer"] for doc in population.base_pop_metrics())
KeyError: 'timer'

**Comment by WLM1ke** [comment]
Судя по сообщению, у вас нет ключа timer у одного из организмов (видимо в следствии некорректного завершения) - надо найти его и удалить из базы.

**Comment by vSINKS** [comment]
Спасибо, помогло!
Скачал и установил MongoDB Compass, глазами нашел запись, создал бэкап БД и удалил ошибочную. После этого всё заработало.
