### ISSUE TITLE
запуск Telegram бота с информированием об ошибках

### ISSUE THREAD

**Issue by vSINKS** [WLM1ke/poptimizer#99]
Добрый день!
Подскажите пожалуйста, каким образом запустить Телеграмм бота? Зашел в каталог data прошелся по командам makefile. Обновил Go до 1.18, заполнил .env TOKEN=<токен от бота>, CHAT_ID=<ID моего аккаунта>. Собрал бинарник, лежит в ~/poptimizer/data/.bin/podata
Бинарник запускать отдельно или он сам запустится вместе с evolve?

**Comment by WLM1ke** [comment]
Не стоит пока этим пользоваться. Есть идея разбить текущую программу на микросервисы и большую часть переписать на Go, кроме самого блока обучения моделей. Пока это самое начало процесса переписывания блока сбора данных - в основном коде никак не используется.

**Comment by vSINKS** [comment]
Принято, спасибо!
